### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by phlippe**
* Consistency of writing 'JAX'
* Putting all installation comments together
* Small edits otherwise

### CODE REVIEW

**Comment by phlippe** [comment]
In simple parallelism, check whether start and end idx are correct (first GPU fits 140k, second 70k, text says together 140k?)

**Comment by phlippe** [comment]
The README doesn't convince well at the moment what this library is really doing, i.e. the abstract key points of why we have it and why someone should use it are not clear enough. Overall, the structure is a bit unclear (e.g. what is the purpose of the `repository` section in `Getting started`?

**Comment by phlippe** [comment]
Personal preference: I put more trust in a library if the examples/shown standard use cases do not need several command line arguments. The details are for the tutorials/examples, here I would stick to the simplest setting there is

**Comment by samuelepapa** [comment]
This branch was merged into the docs branch for further improvement.

**Pull request closed without merging**
